language: node_js
node_js:
  - "10.15.3"
cache:
  directories:
    - node_modules
script:
  - CI=false npm run build && cp ./build/index.html ./build/200.html
deploy:
  provider: surge
  skip_cleanup: true
  domain: print-challenge.kody-koy.me
  project: ./build/
on:
  branch: master